### ISSUE TITLE
Move Dockerfiles to their respective repositories

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/crn_deploy#3]
It will make the images reusable across other projects. Applies to:
- bids-core
- crn-app
- crn-server

It will require setting up config not via COPY or ADD, but by mounting a file in docker-compose.yml. (see https://github.com/NeuroVault/NeuroVault/blob/master/docker-compose.yml#L27)

**Comment by constellates** [comment]
I've started testing out builds using docker hub to build individual repos. Currently the testing is under my username. Do you want to create a docker hub organization and give me access? Or if you give me a name you'd like to use I can probably create an organization and transfer ownership. The minimum is 4 characters so "crn" won't work.

**Comment by chrisgorgo** [comment]
I added you to owners of poldraklab org on docker hub. You can put images
there.

In terms of building I recommend against auto builds and for building the
image on circleci, running tests in it and if they pass pushing the
container to docker hub (preferably with unique versions). See here for an
example: https://github.com/BIDS-Apps/freesurfer/blob/master/circle.yml#L37

**Comment by constellates** [comment]
Looks like I also need admin access on github to add projects to circle CI. Can you either grant me admin privilege on the following repos or add them to circle CI so I can begin setting them up.

https://github.com/poldracklab/crn_server
https://github.com/poldracklab/crn_app
https://github.com/poldracklab/bids-core

**Comment by constellates** [comment]
r

**Comment by constellates** [comment]
Accidentally hit the close and comment button.

**Comment by chrisgorgo** [comment]
done!

**Comment by constellates** [comment]
Alright. CI is setup for the three main repositories. In each case it builds the docker image then runs any linting and tests from the image. If it passes it publishes.

For the crn_server and crn_app projects dev and master branch builds get tagged and published. Dev builds get a dev-<package.json version> tag and a dev-latest tag. Master builds are the same minus the "dev-" prefix.

Only master branch builds get published for the bids-core project and the tagging scheme is more or less the same as the freesurfer tags you linked above.

The "latest" tag is always replaced with the most recent build  ("dev-latest" for dev builds).

And this repo relies solely on docker hub images  and configuration now.
