### ISSUE TITLE
SFTP access is missing?

### ISSUE THREAD

**Issue by chrisgorgo** [poldracklab/crn_deploy#5]
Currently we require SFTP access to the data views for running jobs through Agave. Unless I'm missing something it's not part of the current deployment.

**Comment by constellates** [comment]
I hadn't thought about the possibility of incorporating the SFTP account in the container. Currently it relies on mounted local volumes that are SFTP accessible. I work on moving this inside the container.

**Comment by constellates** [comment]
This is updated and running on both our servers

We're using the following docker image to create an openssh server and make our data directories accessible.
https://github.com/atmoz/sftp

Here are the changes
https://github.com/poldracklab/crn_deploy/blob/master/docker-compose.yml#L39-L48

**Comment by constellates** [comment]
Do you mind if I close this issue out?

**Comment by constellates** [comment]
This has been running on dev and prod for a couple months. Closing. Let me know if you see any issues with the sftp implementation.
